# Generated by Django 5.0.2 on 2024-03-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='finished_videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='finished_videos', to='Courses.video'),
        ),
    ]
