# Generated by Django 5.0.2 on 2024-03-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
