# Generated by Django 5.0.2 on 2024-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_customuser_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
