# Generated by Django 5.0.2 on 2024-04-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_badge_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
