# Generated by Django 5.0.2 on 2024-03-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shippingCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
