# Generated by Django 5.0.2 on 2024-04-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_home'),
        ('Users', '0008_badge_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_choice', models.IntegerField(choices=[(0, '😤'), (1, '🙁'), (2, '😐'), (3, '🙂'), (4, '😀'), (5, '😄')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.customuser')),
            ],
        ),
    ]
