# Generated by Django 5.0.2 on 2024-04-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
        ('Pages', '0004_feedback_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='featured_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
    ]
