# Generated by Django 5.0.2 on 2024-05-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
