# Generated by Django 5.0.2 on 2024-05-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_podcast_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='podcast_banner/'),
        ),
    ]
