# Generated by Django 5.0.2 on 2024-05-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_podcast_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='featuredYoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=10000)),
            ],
        ),
    ]
