# Generated by Django 5.0.2 on 2024-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_alter_featuredyoutubevideo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredyoutubevideo',
            name='url',
            field=models.URLField(max_length=10000),
        ),
    ]
