# Generated by Django 5.0.2 on 2024-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0011_alter_featuredyoutubevideo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredyoutubevideo',
            name='url',
        ),
        migrations.AddField(
            model_name='featuredyoutubevideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
