# Generated by Django 5.0.2 on 2024-05-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_remove_featuredyoutubevideo_url_and_more'),
        ('Users', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('index', models.IntegerField(blank=True, null=True, unique=True)),
                ('points', models.IntegerField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Pages.quest')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.step')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.customuser')),
            ],
        ),
    ]
