# Generated by Django 5.0.2 on 2024-03-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_room_remove_message_room_name_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
