# Generated by Django 5.0.2 on 2024-04-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_section_room_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
