# Generated by Django 5.0.2 on 2024-03-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Users.professor'),
        ),
        migrations.AddField(
            model_name='courseprogression',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progressions', to='Courses.course'),
        ),
        migrations.AddField(
            model_name='courseprogression',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_progressions', to='Users.customuser'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course'),
        ),
        migrations.AddField(
            model_name='level',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='Courses.course'),
        ),
        migrations.AddField(
            model_name='levelprogression',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='Courses.level'),
        ),
        migrations.AddField(
            model_name='levelprogression',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_progressions', to='Users.customuser'),
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Courses.level'),
        ),
        migrations.AddField(
            model_name='exam',
            name='quizzes',
            field=models.ManyToManyField(to='Courses.quiz'),
        ),
        migrations.AddField(
            model_name='video',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Courses.module'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='Courses.video'),
        ),
    ]
