# Generated by Django 5.0.2 on 2024-04-25 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_remove_quiz_answer_usercourseprogress'),
        ('Users', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.customuser'),
        ),
    ]
