# Generated by Django 5.0.2 on 2024-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_alter_usercourseprogress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
