# Generated by Django 5.0.2 on 2024-03-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_mode', models.CharField(choices=[('0', 'a session by yourself alone'), ('1', 'a session just between you and your friends'), ('2', 'a session including you and another group')], default=0, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_hours', models.PositiveIntegerField(blank=True, choices=[(30, '30 Minutes'), (60, '1 Hour'), (90, '1H 30 Minutes'), (120, '2 Hours')], null=True)),
                ('selected_professor', models.CharField(blank=True, choices=[(0, 'az'), (1, '1 zz'), (2, '1H 30zz Minutes')], max_length=150, null=True)),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('schedule', models.DateTimeField()),
                ('Duration', models.DurationField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_private_sessions', to='Users.customuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_private_sessions', to='Users.customuser')),
            ],
        ),
    ]
