# Generated by Django 5.0.2 on 2024-02-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateSessions', '0001_initial'),
        ('Users', '0009_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'a session by yourself alone'), ('1', 'a session just between you and your friends'), ('2', 'a session inculding you and another group')], default='0', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True, null=True)),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.professor')),
            ],
        ),
    ]
