# Generated by Django 5.0.2 on 2024-03-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateSessions', '0002_remove_privatesession_duration_privatesession_cours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesession',
            name='email',
            field=models.EmailField(blank=True, default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='first_name',
            field=models.CharField(blank=True, default='jon', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='last_name',
            field=models.CharField(blank=True, default='doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='phone_number',
            field=models.CharField(blank=True, default=12345678, max_length=15),
            preserve_default=False,
        ),
    ]
