# Generated by Django 5.0.2 on 2024-03-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateSessions', '0003_alter_privatesession_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesession',
            name='session_mode',
            field=models.CharField(blank=True, choices=[(0, 'A session by yourself alone'), (1, 'A session just between you and your friends'), (2, 'A session including you and another group')], default=0, max_length=1, null=True),
        ),
    ]
