# Generated by Django 5.0.2 on 2024-03-26 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
        ('PrivateSessions', '0004_alter_privatesession_session_mode'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesession',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_private_sessions', to='Users.professor'),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_private_sessions', to='Users.customuser'),
        ),
    ]
