# Generated by Django 5.0.2 on 2024-03-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrivateSessions', '0006_alter_privatesession_cours_and_more'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesession',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_private_sessions', to='Users.professor'),
        ),
    ]
