# Generated by Django 5.0.2 on 2024-03-26 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
        ('PrivateSessions', '0007_alter_privatesession_professor'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesession',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions', to='Courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='duration',
            field=models.DurationField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_private_sessions', to='Users.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='schedule',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='session_mode',
            field=models.CharField(choices=[(0, 'A session by yourself alone'), (1, 'A session just between you and your friends'), (2, 'A session including you and another group')], default=0, max_length=1),
        ),
    ]