# Generated by Django 5.0.2 on 2024-04-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='deals')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='Products.product')),
            ],
        ),
    ]
