# Generated by Django 5.0.2 on 2024-04-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_deal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deal',
            new_name='Deals',
        ),
    ]
