# Generated by Django 5.0.2 on 2024-04-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_deal_deals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
    ]
